application: sf-viewer

version: 2015-02-10
runtime: python27
threadsafe: true

api_version: 1

handlers:
- url: /jquery
  static_dir: jquery
- url: /dots
  static_dir: dots
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
- url: /
  static_files: viewer.html
  upload: viewer.html
- url: /about
  static_files: about.html
  upload: about.html
- url: /feedback
  static_files: feedback.html
  upload: feedback.html
- url: /upload
  script: app.app
- url: /lat-lons.js
  static_files: lat-lons.js
  upload: lat-lons.js
- url: /thumb/.*
  script: app.app
- url: /(.*\.(gif|png|jpg|css|js|zip))
  static_files: \1
  upload: (.*\.(gif|png|jpg|css|js|zip))
- url: .*
  script: app.app


builtins:
- remote_api: on
#- datastore_admin: on
